[package]
name = "SushiStake"
version = "3.0.0-rc7"
authors = ["Parity Technologies <mailto:admin@parity.io>"]
edition = "2021"

[dependencies]
ink_primitives = { version = "3.0.0-rc7", path = "../../crates/primitives", default-features = false }
ink_metadata = { version = "3.0.0-rc7", path = "../../crates/metadata", default-features = false, features = ["derive"], optional = true }
ink_env = { version = "3.0.0-rc7", path = "../../crates/env", default-features = false }
ink_storage = { version = "3.0.0-rc7", path = "../../crates/storage", default-features = false }
ink_lang = { version = "3.0.0-rc7", path = "../../crates/lang", default-features = false }

scale = { package = "parity-scale-codec", version = "2", default-features = false, features = ["derive"] }

SushiSwap = { version = "3.0.0-rc7", path = "../../SushiSwap", default-features = false, features = ["ink-as-dependency"] }
SushiBar  = { version = "3.0.0-rc7", path = "../../SushiBar", default-features = false, features = ["ink-as-dependency"] }

scale-info = { version = "1", default-features = false, features = ["derive"], optional = true }

[lib]
name = "SushiStake"
path = "lib.rs"
crate-type = ["cdylib"]

# Needed until https://github.com/paritytech/ink/issues/364 is resolved.
[profile.release]
overflow-checks = false

[features]
default = ["std"]
std = [
    "ink_primitives/std",
    "ink_metadata",
    "ink_metadata/std",
    "ink_env/std",
    "ink_storage/std",
    "ink_lang/std",
    "scale/std",
    "scale-info",
    "scale-info/std",

    "SushiSwap/std",
    "SushiBar/std",
  
]
ink-as-dependency = []

[workspace]
members = [
    "SushiSwap",
   "SushiBar"
    
    
]